apiVersion: v1
kind: Pod
metadata:
  name: department-api
  labels:
    app: department-api
    rel: stable
spec:
  containers:
    - name: department-api
      image: gurramh/department-service:v1.0.0
      ports:
      - containerPort: 8083
      livenessProbe:
        httpGet:
          path: /health/check
          port: 8081
        initialDelaySeconds: 15
        timeoutSeconds: 10
        periodSeconds: 10
        failureThreshold: 1